# Generated by Django 5.0.6 on 2024-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_patient_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="no_of_test_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
